# 1. Site settings
theme: jekyll-theme-minimal
logo: "/assets/logos/logo.jpg"
title: "Daniel Nelson"
author: "Daniel Nelson"
email: "danielnelsoenarto17@gmail.com"
google_analytics:

# 2. Collection
collections:
  posts:
    output: true

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/daniel-nelson-id/
  GitHub: https://github.com/DanielSoenarto/
